#ifndef POV_IMAGE_H
#define POV_IMAGE_H

#include <stdint.h>

/* -----------------------------------------------------------------------
 * Shared image types.
 *
 * These describe how the POV renderer in main.c walks a stored image:
 * column-major packed pixel data plus per-image metadata. Built-in images
 * are generated by tools/bmp_convert.py into eo_image_data.h; user images
 * are converted on-device by pov_bmp.c and stored by pov_user_image.c.
 *
 * The Nv_Metadata layout is written verbatim to the .meta_data flash page
 * by update_metadata() in main.c -- do not reorder fields.
 * ----------------------------------------------------------------------- */

#define POV_IMAGE_MAX_FRAMES   128U

typedef enum {
	NONE = 0,
	ONE_BIT,
	FOUR_BIT,
	FOUR_BIT_FANCY      /* reserved: metadata only, renderer does not implement it yet */
} Image_Display_Mode;

typedef struct {
	uint8_t display_cycles;
	uint8_t cycle_count;
	uint8_t column_height;              /* 8 / 16 / 32 */
	uint8_t max_frame_columns;
	uint8_t frame_columns[POV_IMAGE_MAX_FRAMES];
	uint8_t frame_count;

	Image_Display_Mode mode;

	uint8_t* image_data;               /* absolute flash address of the packed columns */
	uint16_t image_data_length;

} Image_Metadata;

typedef struct {
	uint8_t startup_mode;
	int32_t accel_x_zero;
	int32_t accel_y_zero;
	uint8_t first_run;
	Image_Metadata user_images[2];

} Nv_Metadata;

#endif /* POV_IMAGE_H */
